# Generated by Django 5.2 on 2025-04-15 21:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historicalstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Присутствовал'), ('A', 'Отсутствовал'), ('L', 'Опоздал'), ('E', 'Уваж. причина')], max_length=1, verbose_name='Статус')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время отметки')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Запись о посещаемости',
                'verbose_name_plural': 'Посещаемость',
                'ordering': ['-timestamp'],
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
